### PR TITLE
Merge getSystemDateAndTime and 'timeShift' fixes to master

### PR DESCRIPTION
**Pull request by RogerHardiman**

### CODE REVIEW

**Comment by RogerHardiman** [comment]
I'll be using these fixes on a live project but wanted @agsh and maybe @chriswiggins  to take a look first.

**Comment by RogerHardiman** [comment]
Hi Andrew. I had not thought about 'let' and old NodeJS versions. All my projects use Node v8 or above now and there are other places in the library that use 'let'.
Increasing the minimum version of Node seems to be a good idea

**Comment by chriswiggins** [comment]
This seems to be a good change to me - I don't have anything to test it on currently but LGTM!

**Comment by RogerHardiman** [comment]
@chriswiggins - Many thanks for the quick review.

**Pull request merged**
