### PR TITLE
support https protocol

### PR DESCRIPTION
**Pull request by ManjunathaN**

### CODE REVIEW

**Comment by ManjunathaN** [comment]
Related PR - https://github.com/agsh/onvif/pull/194

**Comment by RogerHardiman** [comment]
This is great. many thanks.
I am wondering if using 'isSecure' (which is more of a 'get' status function) is the right option name, and it would be better called 'useSecure' instead.

**Comment by ManjunathaN** [comment]
> This is great. many thanks.
> I am wondering if using 'isSecure' (which is more of a 'get' status function) is the right option name, and it would be better called 'useSecure' instead.

Thanks. Updated the fieldname.

**Comment by chriswiggins** [comment]
Thanks for the PR! Can you also please include an option to pass secureOptions (options) to the HTTPS client? Most of these cameras will have self-signed certs that I believe node will reject

**Comment by ManjunathaN** [comment]
> Thanks for the PR! Can you also please include an option to pass secureOptions (options) to the HTTPS client? Most of these cameras will have self-signed certs that I believe node will reject

Thanks for the comments. I've modified the code.

**Comment by chriswiggins** [comment]
Awesome @ManjunathaN ! How about an extra-for-experts and creating a https mock server that we can use to test connectivity? I don't think it needs to do the full test suite but just an initial connection would be good

**Comment by RogerHardiman** [comment]
Hi @ManjunathaN 
Thanks for the changes. I've merged them into master.
I had one extra piece of review feedback, in addition to Chris's request to add https to Mock Server for automated testing.
In the Environment Variables, have IS_SECURE.   I asked you to change options.isSecure to options.useSecure which you did. Thank you.   Should we change the Environment Variable to match as well?
I know it is just a comment, but it would match up with the options name.

If you want some help on the Mock server, you can run
```npm run test```

It starts an ONVIF Server on a local port an then gets the ONVIF Library to connect to it.
It uses ONVIF Discovery so does work better on a network with no other ONVIF devices connected (as the discovery phase will detect other cameras on your LAN)

**Comment by ManjunathaN** [comment]
> Awesome @ManjunathaN ! How about an extra-for-experts and creating a https mock server that we can use to test connectivity? I don't think it needs to do the full test suite but just an initial connection would be good

Sorry missed this message. I'll try to create a new PR for the same.

**Comment by ManjunathaN** [comment]
> Hi @ManjunathaN
> Thanks for the changes. I've merged them into master.
> I had one extra piece of review feedback, in addition to Chris's request to add https to Mock Server for automated testing.
> In the Environment Variables, have IS_SECURE. I asked you to change options.isSecure to options.useSecure which you did. Thank you. Should we change the Environment Variable to match as well?
> I know it is just a comment, but it would match up with the options name.
> 
> If you want some help on the Mock server, you can run
> `npm run test`
> 
> It starts an ONVIF Server on a local port an then gets the ONVIF Library to connect to it.
> It uses ONVIF Discovery so does work better on a network with no other ONVIF devices connected (as the discovery phase will detect other cameras on your LAN)

Thanks @RogerHardiman.
Yes, having an env variable HTTPS_MODE or IS_SECURE should do the job. I'll try to check this out over the weekend.

**Pull request merged**
