### PR TITLE
#214 tests in js

### PR DESCRIPTION
**Pull request by agsh**
Just in progress yet. To rewrite tests to refuse coffescript

### CODE REVIEW

**Comment by agsh** [comment]
BTW, I need to think how to apply TravisCI or smth else to test PRs..

**Comment by RogerHardiman** [comment]
Removing coffee script is good. When I've added tests in the past, it was one more thing to learn, so this makes things easier.

Upgrading the dependencies is a good idea.

Roger

**Comment by RogerHardiman** [comment]
I've had a look through the current changes. They all look fine.
Looks like 5 more .coffee files to convert.
(or check in the .js transpiled versions)

**Comment by agsh** [comment]
Thanks! I am still working :smile:

**Pull request merged**
