### PR TITLE
Fix documentation

### PR DESCRIPTION
**Pull request by rodrigograca31**
Hi.

Im not sure why there are differences between the code comments and the docs but shouldn't the docs be auto generated from the code comments to avoid this exact problem? 🤔

Thanks.

### CODE REVIEW

**Comment by RogerHardiman** [comment]
Hi
In ContinuousMove, the velocity for Pan, Tilt and Zoom are -1 to +1   (it is the speed to turn and the direction to turn in).
I see you changed it to be 0 to 1 which I don't think it correct.

**Comment by RogerHardiman** [comment]
The other changes all look good. Thank you for making the changes.

You are correct that the docs should auto generate. @agsh may know if they used to auto generate once, a long time ago.

**Comment by agsh** [comment]
Hello, guys!
Yes, docs can be generated easily via instruction here: https://github.com/agsh/onvif#documentation
Also today I finally rebuilt it with all recent changes: http://agsh.github.io/onvif/
@rodrigograca31 If you fix a liitle bit `README.md` due to the comment from @RogerHardiman about `ContinuousMove`, I'll be glad to approve this PR
BTW: I'm looking for the node.js jobs with relocation from Russia :smile: My LinkedIn: https://www.linkedin.com/in/laptev/

**Comment by agsh** [comment]
@rodrigograca31 Yep, I think that this is my fault in jsdocs. Roger knows a lot more than I do about the ONVIF specification. Just update the PR to fit the specs in the js code. And I'll immediately merge it and update the autogenerated docs as well.

**Comment by rodrigograca31** [comment]
Done.

**Comment by rodrigograca31** [comment]
I just noticed now that theres basically 2 docs.

I was reading `README.md` but theres a branch/pages just for the actual docs:
https://agsh.github.io/onvif/

IMHO the stuff on the `README.md` should be removed and a link to the docs page should be added. otherwise multiple places have to be maintained.

**Comment by agsh** [comment]
@rodrigograca31 Sorry for the late reply. Thanks a lot! 
About the docs: There is a link to the jsdocs in the readme [here](https://github.com/agsh/onvif#api) And yes, I also think that I should cut a lot of the readme. I will set myself this task for the future.

**Pull request merged**
