### PR TITLE
Move examples to folder and ignore in npm

### PR DESCRIPTION
**Pull request by Mudrekh**
Examples are currently listed in the root of repo which adds to clutter. This PR moves them to a unified examples folder. Additionally, the examples are currently being published to NPM. They should not be in the distributed version of module.

### CODE REVIEW

**Comment by agsh** [comment]
Agree with you

**Comment by agsh** [comment]
@Mudrekh But you forgot to change README.md and put the links to the new location, can you do this?

**Comment by RogerHardiman** [comment]
As well as the README, there is also a small error in the actual commit.
Example2 is showing as a DELETE and and then a new ADD. This will erase the full commit history of that file.
Other changes are marked as 'R' which should keep the change history

File Changes
•	M .npmignore (3) 
**•	D example2.js (188)** 
•	R examples/example.js (6) 
**•	A examples/example2.js (187)** 
•	R examples/example3.js (2) 
•	R examples/example4.js (14) 
•	R examples/example5.js (2) 
•	R examples/example6.js (2) 
•	R examples/example7.js (2)

**Comment by Mudrekh** [comment]
@agsh What needed to be changed in the README.md? Just point to the examples folder instead of listing files and a changelog entry?

@RogerHardiman Correct, but I slapped this PR together very quickly. Example 2 was just reformatted because of my autolinter and the applied .eslint config, so git no longer recorgizned the files. Is this a big issue? Its just an example file and not operational code

**Pull request merged**
