### PR TITLE
Changes to PTZ + others (credit @hawkeye64)

### PR DESCRIPTION
**Pull request by chriswiggins**
This is a squash of all the fantastic changes @hawkeye64 has provided

Remove old node versions from TravisCI testing
Add gotoHomePosition and setHomePosition methods (with appropriate test suites)
Fixes some camera’s fault parsing
Bumps NPM package version, adds @hawekeye64 as contributor, fixes some npm deps
Updates readme
Updates test suite XML files to better naming convention

### CODE REVIEW

**Comment by chriswiggins** [comment]
@agsh @hawkeye64 can you both please give this a once-over to make sure you're happy with it? I'll leave it open a week then merge if no complaints!

**Comment by hawkeye64** [comment]
Looks good. I'll be able to test it Monday when I am at work and have access to all of our cameras.

**Comment by hawkeye64** [comment]
+ * /PTZ/ Go to home position
 + * @param {object} options
 + * @param {string} [options.profileToken]
 + * @param {function} callback
 + */
 +Cam.prototype.setHomePosition = function(options, callback) {

This should read "+ * /PTZ/ Set home position"

**Comment by hawkeye64** [comment]
Also, add yourself as a Contributor in package.json :)

**Comment by chriswiggins** [comment]
Ok thanks for spotting! I’ll sort tomorrow. 

Can you flick me an email so we can collaborate on the snapshot module? I’ve done the initial commit and from what I can tell it works well but would like you to do some tests too?

**Comment by hawkeye64** [comment]
How do I get your email? The message said you had replied with an email something-or-rather, and I clicked on it, which took me to your Github account. I didn't see anything there and when I came back, this message was gone. :(

  On January 20, 2018 at 3:52 PM Chris Wiggins <notifications@github.com> wrote:
 
 Ok thanks for spotting! I’ll sort tomorrow. 
  
  Can you flick me an email so we can collaborate on the snapshot module? I’ve done the initial commit and from what I can tell it works well but would like you to do some tests too?

**Pull request merged**
