### PR TITLE
Add User related requests

### PR DESCRIPTION
**Pull request by bl0ggy**
Add ONVIF requests for User management.
I didn't know if I had to create a new .js file or not.

I have not made any test, I don't know how to configure responses in the serverMockup.

### CODE REVIEW

**Comment by RogerHardiman** [comment]
Hi
>https://www.onvif.org/ver10/device/wsdl/devicemgmt.wsdl

These are in the 'device.wsdl' part of the ONVIF spec so they should go in device.js

There are lots of bits of cam.js that should be in device.js too, but that is just historical.

If you could move them into device.js that would be great.

**Comment by sjkummer** [comment]
Would be great to have this merged. Is moving the functions from cam.js to device.js the only thing which is blocking the merge, or is there something else too?

**Comment by RogerHardiman** [comment]
The biggest blocker is lack of time.
We all work on this library in our spare time and I've no spare time at the moment and as I type this I've got to prep for a conference call in 35 mins for my job.

**Comment by sjkummer** [comment]
Ok, I understand.
If there is something that should be changed in this PR, I am willing to do it.

**Review by RogerHardiman — APPROVED** [review]
This looks good and fills in a gap in the library.
I have not tested it but happy to pull it in and then test

**Comment by RogerHardiman** [comment]
I am slowly catching up on Pull Requests.
This is now in master

**Pull request merged**
