### PR TITLE
NTP settings

### PR DESCRIPTION
**Pull request by EastL**
Hello ~ I add the getNTP and setNTP function.

### CODE REVIEW

**Comment by agsh** [comment]
Thanks a lot! I'll merge it tomorrow because I also tried to implement these methods.
I've changed a bit `setSystemDateAndTime` method, if you do not mind, is this ok?

**Comment by EastL** [comment]
OK! Are you want to set NTP server in the setSystemDateAndTime function ?

**Comment by EastL** [comment]
Hello~ can this request be merged ? I also want to merge your new version.....

**Comment by BlueT** [comment]
expecting the merge.

**Comment by agsh** [comment]
Just got it guys! 9963cebd3c6c2e9682bf5c7ffa4f5ce1e1d47231 Sorry for lateness. As you can see on my public contributions on github, I can't handle so much time to do it right now. Also, please-please-please, write tests for your changes, it's just pretty, I'm sure. And in my plans to separate it to synthetic and real tests.
Also we should have separate theme (maybe an issue) to talk about changes in function's arguments an so on... What do you think?

**Comment by agsh** [comment]
And new version in npm is just ready. But I strongly want to split tests (some we cant check with real device, but without real device tests are useless) and to check this commit: 9e215531180b16192ab470daf15d001151ba25c8 This is awesome! Do you have NVE devices on your work?

**Comment by BlueT** [comment]
@agsh what is NVE?

**Comment by agsh** [comment]
@BlueT, network video encoder

**Comment by BlueT** [comment]
erm, I don't think we have...
We got bunches of ONVIF ipcams and some traditional DVRs, but no NVE.

**Comment by BlueT** [comment]
Will @agsh merge this pull request?
We would like to know that if we can keep following the official (@agsh's) branch (prefered) or we have to adopte to our fork (not prefered)...

BTW, @EastL just finished his internship in our company, not sure if he could work on the tests.

**Comment by agsh** [comment]
I've merged this changes 2 days ago. 9963cebd3c6c2e9682bf5c7ffa4f5ce1e1d47231 It cannot be merged automatically so I've done this manually.
To avoid confusion I'll close this issue.
Sure, you can follow this branch, all your commits will be accepted.

**Pull request closed without merging**
