### PR TITLE
fix get UTC time error,some cam do not return the UTC time

### PR DESCRIPTION
**Pull request by leidebin**

### CODE REVIEW

**Comment by RogerHardiman** [comment]
Which camera (make and model) is this needed for? Thanks

**Comment by leidebin** [comment]
here is the deviceinfo
{"deviceInfo":{"manufacturer":"Technology","model":"IPC","firmwareVersion":"14.00.00.57","serialNumber":3529616,"hardwareId":"Ver 2.1"}

**Comment by RogerHardiman** [comment]
Thanks for the information. I have an IPS Eye01 camera in my office.

Could you check the XML that you get back from getSystemDateAndTime please?
Can you see if there is a LocalDateTime value in the XML (instead of UTCDateTime).

If there is a "LocalDateTime" then we need to use that time so we can calculate the correct "timeShift" value.

Thanks

```
      <tds:GetSystemDateAndTimeResponse>
         <tds:SystemDateAndTime>
              ........
            <tt:UTCDateTime>
               .......
            </tt:UTCDateTime>
            <tt:LocalDateTime>
               <tt:Time>
                  <tt:Hour>9</tt:Hour>
                  <tt:Minute>2</tt:Minute>
                  <tt:Second>17</tt:Second>
               </tt:Time>
               <tt:Date>
                  <tt:Year>2016</tt:Year>
                  <tt:Month>10</tt:Month>
                  <tt:Day>29</tt:Day>
               </tt:Date>
            </tt:LocalDateTime>
         </tds:SystemDateAndTime>
      </tds:GetSystemDateAndTimeResponse>
```

**Comment by leidebin** [comment]
I think the maker not implement the GetSystemDateAndTime function

-------------------------------------------------
HTTP/1.1 200 OK
Server: gSOAP/2.8
Content-Type: application/soap+xml; charset=utf-8
Content-Length: 1239
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:tdn="http://www.onvif.org/ver10/network/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl">
  <SOAP-ENV:Body>
    <tds:GetSystemDateAndTimeResponse>
      <tds:SystemDateAndTime />
    </tds:GetSystemDateAndTimeResponse>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by leidebin** [comment]
HTTP/1.1 200 OK
Server: gSOAP/2.8
Content-Type: application/soap+xml; charset=utf-8
Content-Length: 1239
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:tdn="http://www.onvif.org/ver10/network/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl">
  <SOAP-ENV:Body>
    <tds:GetSystemDateAndTimeResponse>
      <tds:SystemDateAndTime />
    </tds:GetSystemDateAndTimeResponse>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by leidebin** [comment]
`HTTP/1.1 200 OK
Server: gSOAP/2.8
Content-Type: application/soap+xml; charset=utf-8
Content-Length: 1239
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:tdn="http://www.onvif.org/ver10/network/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl">
  <SOAP-ENV:Body>
    <tds:GetSystemDateAndTimeResponse>
      <tds:SystemDateAndTime />
    </tds:GetSystemDateAndTimeResponse>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**Comment by agsh** [comment]
Hi! Today the result of GetSystemDateAndTime response is very important, because it is used in SOAP authorization https://github.com/agsh/onvif/blob/master/lib/cam.js#L775
I'm not sure that we should use cams that doesn't support ONVIF protocol in that major cases.

**Comment by RogerHardiman** [comment]
Can I ask if the camera has been configured with a valid time and date. For example some Axis cameras can be set to ignore ONVIF commands until after they have got the correct time from a NTP time server. (this is because the correct time is critical in SOAP authorisation)

Can you check if the camera is getting the correct time please?

**Comment by agsh** [comment]
@RogerHardiman agree with you.

**Comment by Zombitch** [comment]
Any chance to have this pull request merged with the main branch ? (I got the same problem than the author).

**Comment by RogerHardiman** [comment]
can you tell us what type of camera you are using (make and model) please and if the camera is linked to a NTP time source.

**Comment by Zombitch** [comment]
@RogerHardiman, for sure : 

My device is an IP/Onvif Camera :
Name : [HiKam A7](https://www.amazon.com/HiKam-A7-Wireless-Waterproof-Recording/dp/B01FSGGP04/ref=cm_cr_arp_d_product_top?ie=UTF8) 
Manufacturer: Technology
Model: IPC

However the manufacturer did not implement GetSystemDateAndTime Onvif function... While with the android application (Hikam) I can set the camera date time.

Thanks.

**Comment by Seikon** [comment]
It sounds strange. Maybe the vendor has its own way of implementing NTP but does not belong to ONVIF standard and you can't set by this way. you could ask for vendor if yout onvif camera has this onvif method implemented.

**Comment by Zombitch** [comment]
@Seikon , The manufacturer support is not able to answer that question and proposes me to buy the next camera version which should be more ONVIF compliant ... I just laugh at this answer... 

Then my question remain : can we expect to have this pull request merge to the main branch ?

I read the answer @RogerHardiman : 

> this is because the correct time is critical in SOAP authorisation

And i can only agree with him, however, this pull request will make the agsh/onvif project usable for those who have been duped by unscrupulous manufacturers that implement less than half of ONVIF spec.

Anyway, thanks for your explanation and helps.

**Comment by RogerHardiman** [comment]
@Zombitch   is it possible you could do some extra checks for us please?
Are you able to run ONVIF Device Manager on Windows, and run Wireshark, and make a log of how ODM talks to the camera.
I'm interested to see if the camera returns the DateAndTime for ODM, perhaps if the request XML is formatted slightly differently.

**Comment by trycoon** [comment]
One model of camera that I'm using has this same problem, no datetime is returned and therefor I get the "Cannot read property '0' of undefined"-error as above.
The XML returned is:
"<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope                    >
<SOAP-ENV:Header />
<SOAP-ENV:Body>
<tds:GetSystemDateAndTimeResponse>
<tds:SystemDateAndTime />
</tds:GetSystemDateAndTimeResponse>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>


"

The camera is a HOSAFE.COM SV2MB1W, http://www.dx.com/p/hosafe-com-sv2mb1w-1080p-outdoor-wireless-ip-security-camera-au-plug-460046#.WkLsLHXia90

I don't understand the purpose of getSystemDateAndTime in the connect-function since the returned date is not used anyware: https://github.com/agsh/onvif/blob/a21199c93b0f9d52387e0f368d3425ac6cb6dff6/lib/cam.js#L103

Is this feature mandatory? Reading the specs says "A device shall provide the UTCDateTime information although the item is marked as optional to ensure backward compatibility.", I read is as it's optional. https://www.onvif.org/specs/core/ONVIF-Core-Specification-v210.pdf

**Comment by tetreum** [comment]
Could we please merge this? It stills happen with chinese cameras like Sricam SP009

**Comment by tetreum** [comment]
> @tetreum This issue conflict with master branch that moved forward.
> I've pushed th master a little fix for this issue:
> [2e2a421#diff-7b92c408c239591ade8dacbb615bf9eaR268](https://github.com/agsh/onvif/commit/2e2a4218c4ebb7d34b92396118562ac6ea95bd97#diff-7b92c408c239591ade8dacbb615bf9eaR268)
> Can you test it?

Sorry i had github login problems. Yes, it works for me :)

**Pull request closed without merging**
