### PR TITLE
Do not pull events if creating the pull-point subscribtion failed.

### PR DESCRIPTION
**Pull request by sjkummer**
Do not pull events if creating the pull-point subscribtion failed.

### CODE REVIEW

**Comment by agsh** [comment]
@sjkummer Hello! Thanks for the PR! It seems that your branch is a little bit older than the origin/master: `This branch is 1 commit ahead, 129 commits behind agsh/onvif:master.` :smile: 
Maybe this bug is already fixed in the current version. Can you check?

**Comment by sjkummer** [comment]
@agsh Yes, forgot to create a PR backn then 😅 will run a test with the newest version

**Comment by sjkummer** [comment]
I synced with master. From what I see, this exception can still occur.

Since this uncatched exception takes place within the library, an application that uses this library does not have a clean way to catch it and wll crash unless it overrides the general uncaughtException handler of the process which is not recommended.

**Comment by agsh** [comment]
@sjkummer Sorry for the late response. Thanks a lot for the PR! Should I bump the version in the npm?

**Pull request merged**
