### PR TITLE
xml change to discover more cameras

### PR DESCRIPTION
**Pull request by sousandrei**
Changed the probe XML to discover more cameras in the network, probably newer ones

### CODE REVIEW

**Comment by chriswiggins** [comment]
Hi @sousandrei - what camera models have you tested this with?

**Comment by sousandrei** [comment]
@chriswiggins AXIS M1014 and AXIS P5534

**Comment by agsh** [comment]
I'll check also [ODM](https://sourceforge.net/projects/onvifdm/) SOAP message to find out wright one.
I've found out only two major differences: in namespacing and an empty <Scopes /> tag.

**Comment by sousandrei** [comment]
@chriswiggins VIVOTEK FD8136, VIVOTEK IP8337H, AXIS M1014, AXIS Q1755 and INTELBRAS VIP-S3120, but i think INTELBRAS rebrands cameras so probably its a DAHUA IPC-HFW1120S-W with rebranded firmware (?)

**Comment by agsh** [comment]
related #30 issue

**Pull request merged**
